project:
  type: website
  output-dir: docs
  resources: 
    - projects/**

website:
  title: "My Reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Einet CE
        menu:
          - text: Overview
            href: projects/ence/index.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



